version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - backend-network

  proxy:
    container_name: proxy-server
    build:
      context: .
      dockerfile: Dockerfile.proxy
    depends_on:
      - backend
    networks:
      - backend-network
      - client-network

  client:
    container_name: client-server
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - backend
      - proxy
    networks:
      - client-network

networks:
  backend-network:
  client-network:
    